# Generated by Django 5.1.1 on 2024-09-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cobertura', models.IntegerField()),
                ('raca', models.TextField(max_length=255)),
                ('brinco', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('data', models.IntegerField()),
                ('reprodutor', models.TextField(max_length=255)),
                ('peso', models.IntegerField()),
                ('ecc', models.IntegerField()),
                ('tipo_acasalamento', models.IntegerField()),
                ('tipo_estro', models.IntegerField()),
            ],
        ),
    ]
