# Generated by Django 5.1.1 on 2024-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.ImageField(upload_to=''),
        ),
    ]
